### ISSUE TITLE
URGENT: typed_title_string.rb:49:in split_title': undefined method sub' for #Array

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-bib#30]
From @petithug in https://github.com/metanorma/metanorma-ietf/issues/97#issuecomment-680259872

> Now in fact I thought there was two bugs, one hiding the other. If I replace the bibliography by one generated by "relaton --convert", I now have an error in Ruby:

```sh
/var/lib/gems/2.5.0/gems/relaton-bib-1.2.4/lib/relaton_bib/typed_title_string.rb:49:in split_title': undefined method sub' for #Array:0x0000562b97a099c0 (NoMethodError)
Did you mean? sum
```

@andrew2net can you help fix this soon? Thanks!

**Comment by andrew2net** [comment]
@ronaldtse can you explain how to reproduce this issue?

**Comment by ronaldtse** [comment]
@andrew2net please see https://github.com/metanorma/metanorma-ietf/issues/97#issuecomment-680259872 for method to reproduce. Thanks!

**Comment by andrew2net** [comment]
@ronaldtse this issue caused by metanorma-standoc. The line of [code](https://github.com/metanorma/metanorma-standoc/blob/aa5d9218a830b878e0096c88b9630d17e964de5a/lib/asciidoctor/standoc/cleanup_ref.rb#L206) converts a Hash of title:
```ruby
{
  "conten"=>"AsciiRFC: Authoring Internet-Drafts And RFCs Using AsciiDoc",
  "language"=>"en",
  "script"=>"Latn",
  "format"=>"text/plain"
}
```
into an Array:
```ruby
[
  ["conten", "AsciiRFC: Authoring Internet-Drafts And RFCs Using AsciiDoc"],
  ["language", "en"],
  ["script", "Latn"],
  ["format", "text/plain"]
]
```
The relaton accepts a title as Hash or String.
@opoudjis looks like the code assumes the `bib["title"]` is a String, but in this case, it's a Hash. We should use `[bib["title"]]` instead of `Array(bib["title"])`.  I can fix it if you agree.

**Comment by andrew2net** [comment]
@ronaldtse the issue is fixed. It needs to use the latest matanorma. Additionally, there were some errors in the AsciiBib file. To get correct AsciiBib update relaton-bib to the latest version (1.3.1).
