### ISSUE TITLE
Add type to phone

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-bib#84]
Also has come up in https://github.com/metanorma/metanorma-nist/issues/277:

We have (for reasons of legacy) a type on phone, to allow us to differentiate fax numbers from normal phone numbers:

````
phone = element phone { 
  attribute type { text }?,
  text }
````

This is not captured in relaton-bib currently: it gives no way of differentiating phones from fax numbers.

**Comment by andrew2net** [comment]
@opoudjis to represent `phone`, `email`, and `uri` nodes Relaton uses class `RelatonBib::Contact`. The class has `type` attribute that denotes type of contact, i.e. *phone*, *email*, or *uri*. I see that `phone` and `uri` nodes can have their own types.
Since `RelatonBib::Contact#type` is already used, I'm going to add `RelatonBib::Contact#subtype` for `phone[@type]` and `uri[@type]` representation. We also can have `email[@type]` if you allow it in the grammar.

**Comment by opoudjis** [comment]
I wouldn't be surprised if I add email/type eventually. OK.

**Comment by ronaldtse** [comment]
It’s increasingly clear we should just use the vCard model…

**Comment by andrew2net** [comment]
And we heed to change Relaton YAML output from:
```yaml
  ...
  contact:
    - phone: 223322
```
to
```yaml
  ...
  contact:
    - phone: 223322
      type: mobile
  ...
```
